stages:
  - build
 # - test
  - deploy
  
  
composer:  
  stage: build
  script:
    - cd  ${CI_PROJECT_DIR}
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  

deploy_to_production:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: https://poll.fortunejack.com
  script:
    - cd  ${CI_PROJECT_DIR}
    - echo "$PROD_ENV" > .env
    - "rsync -ar --exclude-from='.rsync_excludes' --delete-before --delete-excluded . 127.0.0.1::poll.fortunejack.com"

